
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/yast/head/containers/yast-ruby:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v1

    - name: Inspect Installed Packages
      run: rpm -qa | sort

    - name: Unit Tests
      run: rake test:unit

  Rubocop:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/yast/head/containers/yast-ruby:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v1

    - name: Inspect Installed Packages
      run: rpm -qa | sort

    - name: Rubocop
      run: rake check:rubocop

  Package_and_POT:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/yast/head/containers/yast-ruby:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v1

    - name: Inspect Installed Packages
      run: rpm -qa | sort

    - name: Package Build
      run: yast-travis-ruby -o package

    - name: POT Check
      run: yast-travis-ruby -o pot

  Yardoc_and_Perl:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/yast/head/containers/yast-ruby:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v1

    - name: Inspect Installed Packages
      run: rpm -qa | sort

    - name: Yardoc
      run: yast-travis-ruby -o yardoc

    - name: Perl Syntax
      run: yast-travis-ruby -o perl_syntax
